from .book_class import Book

BOOKS = [
    Book(
        id=1,
        title="The Great Gatsby",
        author="F. Scott Fitzgerald",
        description="The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
        published_year="1925",
        rating=3,
    ),
    Book(
        id=2,
        title="To Kill a Mockingbird",
        author="Harper Lee",
        description="The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
        published_year="1960",
        rating=4,
    ),
    Book(
        id=3,
        title="1984",
        author="George Orwell",
        description="A dystopian novel set in Airstrip One, formerly Great Britain, a province of the superstate Oceania.",
        published_year="1949",
        rating=5,
    ),
    Book(
        id=4,
        title="Pride and Prejudice",
        author="Jane Austen",
        description="A romantic novel of manners that centers on the character Elizabeth Bennet.",
        published_year="1813",
        rating=4,
    ),
    Book(
        id=5,
        title="The Catcher in the Rye",
        author="J.D. Salinger",
        description="A novel about personal identity, belonging, loss, and connection.",
        published_year="1951",
        rating=3,
    ),
    Book(
        id=6,
        title="The Hobbit",
        author="J.R.R. Tolkien",
        description="A children's fantasy novel and prelude to The Lord of the Rings.",
        published_year="1937",
        rating=5,
    ),
    Book(
        id=7,
        title="Moby Dick",
        author="Herman Melville",
        description="An epic tale of the sea and a detailed portrait of the whaling industry.",
        published_year="1851",
        rating=2,
    ),
    Book(
        id=8,
        title="War and Peace",
        author="Leo Tolstoy",
        description="A novel that chronicles the French invasion of Russia and the impact of the Napoleonic era.",
        published_year="1869",
        rating=4,
    ),
    Book(
        id=9,
        title="The Adventures of Huckleberry Finn",
        author="Mark Twain",
        description="A novel about the adventures of a young boy and a runaway slave as they travel down the Mississippi River.",
        published_year="1884",
        rating=4,
    ),
    Book(
        id=10,
        title="The Diary of a Young Girl",
        author="Anne Frank",
        description="The writings from the Dutch language diary kept by Anne Frank while she was in hiding during World War II.",
        published_year="1947",
        rating=5,
    ),
    Book(
        id=11,
        title="Computer Science Prop",
        author="Christophe Moreira",
        description="A nice book about computer science. It is a must-read for all computer science students.",
        published_year="2021",
        rating=5,
    ),
    Book(
        id=12,
        title="Be Fast with FastAPI",
        author="Christophe Moreira",
        description="A book about FastAPI. It is a must-read for all FastAPI developers.",
        published_year="2024",
        rating=5,
    ),
]
